name: Upgrade Unity version

on:
  workflow_dispatch:
    inputs:
      unityVersion:
        description: 'Unity Version'
        required: true
        type: string

jobs:
  upgrade-unity-version:
    name: Upgrade Unity version and packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - run: |
          echo "Upgrading to Unity Version: $UNITY_VERSION"
        env:
          UNITY_VERSION: ${{ inputs.unityVersion }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-

      - name: Build project
        uses: JohannesDeml/unity-builder@d19141044df950835040e83b2b6d443d10b16d13
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildMethod: UnityBuilderAction.UnityPackageScripts.UpgradeAllPackagesToVerifiedVersion
          unityVersion: ${{ inputs.unityVersion }}
          targetPlatform: WebGL
          buildName: ${{ needs.variables.outputs.BUILD_NAME }}
          allowDirtyBuild: true

      - name: Log git status
        run: git status
